print("{")
print("  \"Ukraine\": {")
print("    \"people\": [\"Vlad\", \"Yaroslav\", \"Ira\", \"Serhii\"],")
print("    \"count\": 4")
print("  }")
print("  \"USA\": {")
print("    \"people\": [\"John\", \"Bob\", \"Chris\"],")
print("    \"count\": 3")
print("  }")
print("  \"Paris\": {")
print("    \"people\": [\"Sarah\", \"Elizabeth\"],")
print("    \"count\": 2")
print("  }")
print("  \"India\": {")
print("    \"people\": [\"Ramesh\", \"Shawn\"],")
print("    \"count\": 2")
print("  }")
print("}")